version: 2.1

orbs:
  python: circleci/python@4.0.0
  aws-cli: circleci/aws-cli@5.1
  aws-ecr: circleci/aws-ecr@9.0
  terraform: circleci/terraform@3.7.0

jobs:
  code-linter:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt  
          args: 'ruff'
      
      - run:
          name: Run Ruff Linter
          command: ruff check app
          
      - run:
          name: Check Ruff Formatting
          command: ruff format --check app
  build-and-push:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout
      
      - aws-ecr/build_and_push_image:
          account_id: $AWS_ACC_ID
          auth:
            - aws-cli/setup:
                role_arn: $AWS_ROLE_ARN
          create_repo: true
          path: ./docker
          push_image: false
          region: $aws_region
          repo: $ecr_repo_name
          tag: $image_tag
      - run:
          name: Tests for docker image
          command: |
            set -x

            docker run -d -p 8000:8000 -e "HOST=0.0.0.0" --name test_app $ECR_REGISTRY/$ecr_repo_name:$image_tag

            sleep 5

            curl --fail http://localhost:8000/health
            CURL_STATUS=$?

            docker stop test_app && docker rm test_app

            if [ $CURL_STATUS -ne 0 ]; then
              echo "Health check failed!"
              exit 1
            else
              echo "Health check passed successfully!"
              exit 0
            fi

            set +x
      - aws-ecr/push_image:
          account_id: $AWS_ACC_ID
          region: $aws_region
          repo: $ecr_repo_name
          tag: $image_tag
  provision-infrastructure:
    executor: terraform/default

    steps:
      - checkout

      - aws-cli/setup:
          role_arn: $AWS_ROLE_ARN
          region: $aws_region

      - terraform/init:
          path: ./infrastructure/terraform
          backend_config: 'region=$aws_region,bucket=$bucket_name,key=$tf_state_path'
      - terraform/validate:
          path: ./infrastructure/terraform
      - terraform/fmt:
          path: ./infrastructure/terraform
      - terraform/plan:
          out: 'deployment.tfplan'
          path: ./infrastructure/terraform
          var: >-
            github_profile="<< pipeline.git.repo_owner >>",
            github_repo_name="<< pipeline.git.repo_name >>",
            aws_region="$aws_region",
            extension_id="$extension_id",
            image_tag="$image_tag",
            container_host="$container_host",
            container_port="$container_port",
            instance_type="$ec2_instance"
      - terraform/apply:
          path: ./infrastructure/terraform
          plan: 'deployment.tfplan'
      
      - persist_to_workspace:
          root: .
          paths:
            - infrastructure/ansible/hosts.ini

  deploy:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - attach_workspace:
          at: .

      - aws-cli/setup:
          role_arn: $AWS_ROLE_ARN
          region: $aws_region
      
      - run:
          name: Install Ansible and run playbook
          command: |
            sudo apt-get update -y
            sudo apt-get install -y python3-pip python3-setuptools

            sudo pip3 install --upgrade pip
            sudo pip3 install ansible boto3 botocore

            curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
            sudo dpkg -i session-manager-plugin.deb

            # Install Ansible AWS Collection
            ansible-galaxy collection install community.aws

            cd infrastructure/ansible && ansible-playbook deploy.yml -e \
              "aws_region=$aws_region ecr_registry=$ECR_REGISTRY \
              image_name=$ecr_repo_name image_tag=$image_tag \
              extension_id=$extension_id docker_host=$container_host \
              instance_port=$container_port env=dev \
              ansible_aws_ssm_region=$aws_region ansible_aws_ssm_bucket_name=$bucket_name"

              
workflows:
  deploy-to-aws: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - code-linter
      # - python/test:
      #     test-tool: pytest
      #     requires:
      #       - code-linter
      - build-and-push:
          context: CircleCI_OIDC_Token
      - provision-infrastructure:
          context: CircleCI_OIDC_Token
          requires:
            - build-and-push
      - deploy:
          requires:
            - provision-infrastructure