version: 2.1

orbs:
  python: circleci/python@4.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      
      - run:
          name: Run Ruff Linter
          command: ruff check app
          
      - run:
          name: Check Ruff Formatting
          command: ruff format --check app
      
      - python/test:
          test-tool: pytest

workflows:
  deploy-to-aws: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test