version: 2.1

orbs:
  python: circleci/python@4.0.0

jobs:
  code-linter:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout
      
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: test-requirements.txt  
          args: 'ruff'
      
      - run:
          name: Run Ruff Linter
          command: ruff check app
          
      - run:
          name: Check Ruff Formatting
          command: ruff format --check app
      
workflows:
  deploy-to-aws: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - code-linter
      - python/test:
          test-tool: pytest
          requires:
            - code-linter