name: Containerized Lambda CI/CD

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "backend" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true # Instantly caches dependencies to speed up future runs
        cache-dependency-glob: "pyproject.toml"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"

    - name: Run Ruff (Lint & Format Check)
      run: |
        uv ruff check src/
        uv ruff format --check src/
    - name: Run Pytest Suite
      run: |
        uv run pytest
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
